Built a script for converting index.rst to main.ptx
bnmnetp/Runestone2PreTeXt pull request #7
Opened 2022-07-12 20:02 UTC by knakaj

2022-07-12 22:59 UTC, bnmnetp requested changes

2022-07-12 22:59 UTC, bnmnetp commented on index2main.py
> +        ttx.write("    <backmatter>\n")
All of the following could be converted to a single write using a triple-quoted string.  `"""` or `'''`. this is often much easier to read.

2022-07-12 22:59 UTC, bnmnetp commented on index2main.py
> +for root, dirs, files in os.walk("."):
I think this is dangerous... You don't need a nested loop here.  In RST there should only be a single root index.rst file. But nothing prevents a subdirectory from having an index.rst file that contains important content.  I would suggest that you just have a parameter to the script that contains the path to the index.rst you want to convert.

2022-07-29 19:29 UTC, knakaj commented
I made the suggested changes to the script, tested it, and it works well. Let me know if any further changes are needed.

2022-08-01 15:46 UTC, merged